# Generated by Django 4.1.1 on 2022-11-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodisco',
            name='nombre',
            field=models.CharField(choices=[('cd', 'CD'), ('vinilo', 'Vinilo')], max_length=30),
        ),
    ]
