# Generated by Django 4.1.1 on 2022-11-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tipousuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
