# Generated by Django 4.1.1 on 2022-11-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_disco_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodisco',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
